// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"life_notepad_api/internal/dao/internal"
)

// internalChatDao is internal type for wrapping internal DAO implements.
type internalChatDao = *internal.ChatDao

// chatDao is the data access object for table t_chat.
// You can define custom methods on it to extend its functionality as you wish.
type chatDao struct {
	internalChatDao
}

var (
	// Chat is globally public accessible object for table t_chat operations.
	Chat = chatDao{
		internal.NewChatDao(),
	}
)

// Fill with you ideas below.
