// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file.go as you wish.
// =================================================================================

package file
